Repository hashicorp/terraform-plugin-framework, pull requests merged in 2021-09, with the labels that each got.

#122 tfsdk: Exit early in TestServerPlanResourceChange on error diagnostics
  tfsdk/serve_test.go
Labels: bug

#108 docs/design: Initial diagnostics design
  docs/design/diagnostics.md
Labels: documentation, design-doc

#129 attr: Add attribute path parameter to (TypeWithValidate).Validate() method
  attr/type.go
  internal/reflect/interfaces.go
  internal/reflect/map.go
  internal/reflect/number.go
  internal/reflect/number_test.go
  internal/reflect/pointer.go
  internal/reflect/pointer_test.go
  internal/reflect/primitive.go
  internal/reflect/primitive_test.go
  internal/reflect/slice.go
  internal/reflect/struct.go
  internal/testing/types/boolwithvalidate.go
  internal/testing/types/diags.go
  internal/testing/types/numberwithvalidate.go
  internal/testing/types/stringwithvalidate.go
  tfsdk/attribute_test.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: enhancement

#123 tfsdk: Ensure other attribute plan modifiers are called after errors
  tfsdk/attribute.go
  tfsdk/attribute_plan_modification.go
  tfsdk/attribute_test.go
  tfsdk/resource.go
  tfsdk/schema.go
  tfsdk/serve_resource_attribute_plan_modifiers_test.go
  tfsdk/serve_test.go
Labels: bug

#133 tfsdk: Properly set attribute path in (Plan).SetAttribute() and (State).SetAttribute() reflection diagnostics
  .changelog/133.txt
  internal/reflect/interfaces.go
  internal/reflect/map.go
  internal/reflect/number.go
  internal/reflect/outof.go
  internal/reflect/pointer.go
  internal/reflect/primitive.go
  internal/reflect/slice.go
  internal/reflect/struct.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: bug

#130 docs/design: Initial import design document
  docs/design/import.md
Labels: design-doc

#126 types: Support Set and SetType
  .changelog/126.txt
  internal/reflect/slice.go
  internal/reflect/struct_test.go
  tfsdk/attribute.go
  tfsdk/attribute_test.go
  tfsdk/nested_attributes.go
  tfsdk/schema.go
  tfsdk/schema_test.go
  tfsdk/serve_provider_test.go
  tfsdk/serve_test.go
  tfsdk/state_test.go
  types/object_test.go
  types/set.go
  types/set_test.go
Labels: enhancement

#149 tfsdk: Initial ImportResourceState support
  .changelog/149.txt
  tfsdk/request_import.go
  tfsdk/resource.go
  tfsdk/resource_import.go
  tfsdk/response_import.go
  tfsdk/serve.go
  tfsdk/serve_data_source_config_validators_test.go
  tfsdk/serve_data_source_validate_config_test.go
  tfsdk/serve_import.go
  tfsdk/serve_import_test.go
  tfsdk/serve_provider_test.go
  tfsdk/serve_resource_attribute_plan_modifiers_test.go
  tfsdk/serve_resource_config_validators_test.go
  tfsdk/serve_resource_import_state_test.go
  tfsdk/serve_resource_one_test.go
  tfsdk/serve_resource_two_test.go
  tfsdk/serve_resource_validate_config_test.go
  tfsdk/serve_test.go
Labels: enhancement

#164 tfsdk: Omit ImportedResource from response if error during protocol conversion
  tfsdk/serve_import.go
  tfsdk/serve_import_test.go
Labels: bug

#166 types: Support Float64, Float64Type, Int64, and Int64Type
  .changelog/166.txt
  tfsdk/serve_provider_test.go
  tfsdk/serve_test.go
  types/float64.go
  types/float64_test.go
  types/int64.go
  types/int64_test.go
  types/primitive.go
  types/primitive_test.go
Labels: enhancement, sdkv2-parity, types

#165 tfsdk: Allow Plan and State SetAttribute to create attribute paths
  .changelog/165.txt
  internal/testing/types/listwithvalidate.go
  internal/testing/types/mapwithvalidate.go
  internal/testing/types/setwithvalidate.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/schema.go
  tfsdk/serve_import_test.go
  tfsdk/state.go
  tfsdk/state_test.go
  tfsdk/tftypes_transform.go
  tfsdk/tftypes_value.go
  tfsdk/tftypes_value_test.go
Labels: bug

#176 Fix planning.
  tfsdk/schema.go
  tfsdk/schema_test.go
  tfsdk/serve.go
  tfsdk/serve_provider_test.go
  tfsdk/serve_resource_three_test.go
  tfsdk/serve_resource_two_test.go
  tfsdk/serve_test.go
Labels: bug

#184 tfsdk: Check ProposedNewState for State differences before marking unknowns for Computed-only attributes in plans
  tfsdk/serve.go
  tfsdk/serve_resource_attribute_plan_modifiers_test.go
  tfsdk/serve_test.go
Labels: bug

#185 tfsdk: Return null value when missing from Config, Plan, and State GetAttribute() method
  .changelog/185.txt
  tfsdk/attribute_test.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: bug, reflection
