Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-11, with the labels that each got.

#530 Fix Typo
  website/docs/plugin/framework/index.mdx
Labels: documentation

#534 tfsdk: Document and clarify GetAttribute and SetAttribute further
  tfsdk/config.go
  tfsdk/plan.go
  tfsdk/state.go
  website/docs/plugin/framework/accessing-values.mdx
  website/docs/plugin/framework/writing-state.mdx
Labels: documentation

#537 website: Split resource lifecycle management into separate pages
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/resources/create.mdx
  website/docs/plugin/framework/resources/delete.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/read.mdx
  website/docs/plugin/framework/resources/update.mdx
Labels: documentation

#536 types: Add Typable and Valuable Interfaces
  .changelog/536.txt
  internal/fwserver/attr_value.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/block_validation.go
  internal/testing/types/listnestedattributescustom.go
  internal/testing/types/mapnestedattributescustom.go
  internal/testing/types/setnestedattributescustom.go
  internal/testing/types/singlenestedattributescustom.go
  types/bool.go
  types/float64.go
  types/int64.go
  types/list.go
  types/map.go
  types/number.go
  types/object.go
  types/primitive.go
  types/set.go
  types/string.go
Labels: enhancement

#544 tfsdk: Switch Config, Plan, and State type Schema fields to interface
  .changelog/544.txt
  internal/fwserver/schema.go
  internal/fwserver/server_createresource.go
  internal/fwserver/server_deleteresource.go
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_readdatasource.go
  internal/fwserver/server_updateresource.go
  internal/fwserver/server_upgraderesourcestate.go
  tfsdk/config.go
  tfsdk/plan.go
  tfsdk/state.go
Labels: enhancement, breaking-change

#545 internal/fwschema: Add NestedAttributeObject and NestedBlockObject interfaces
  .changelog/543.txt
  internal/fwschema/block.go
  internal/fwschema/errors.go
  internal/fwschema/fwxschema/nested_attribute_object_validation.go
  internal/fwschema/fwxschema/nested_block_object_validators.go
  internal/fwschema/nested_attribute.go
  internal/fwschema/nested_attribute_object.go
  internal/fwschema/nested_block.go
  internal/fwschema/nested_block_object.go
  internal/fwschema/schema.go
  internal/fwschema/underlying_attributes.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_validation.go
  internal/fwserver/block_validation_test.go
  internal/testing/testschema/blockwithlistvalidators.go
  internal/testing/testschema/blockwithobjectvalidators.go
  internal/testing/testschema/blockwithsetvalidators.go
  internal/testing/testschema/nested_attribute_object.go
  internal/testing/testschema/nested_attribute_object_with_validators.go
  internal/testing/testschema/nested_block_object.go
  internal/testing/testschema/nested_block_object_with_validators.go
  internal/testing/testschema/schema.go
  internal/toproto5/block.go
  internal/toproto5/schema_attribute.go
  internal/toproto6/block.go
  internal/toproto6/schema_attribute.go
  tfsdk/attribute.go
  tfsdk/block.go
  tfsdk/nested_attribute_object.go
  tfsdk/nested_block_object.go
  tfsdk/schema.go
Labels: enhancement

#552 Amend Plan Resource Change To Allow For Optional Blocks
  .changelog/552.txt
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_planresourcechange_test.go
Labels: bug

#553 provider/schema: Initial package
  .changelog/553.txt
  internal/fwserver/server.go
  internal/fwserver/server_configureprovider_test.go
  internal/fwserver/server_getproviderschema_test.go
  internal/fwserver/server_validateproviderconfig_test.go
  internal/proto5server/server_configureprovider_test.go
  internal/proto5server/server_getproviderschema_test.go
  internal/proto5server/server_prepareproviderconfig_test.go
  internal/proto6server/server_configureprovider_test.go
  internal/proto6server/server_getproviderschema_test.go
  internal/proto6server/server_validateproviderconfig_test.go
  internal/testing/testprovider/provider.go
  provider/provider.go
  provider/schema.go
  provider/schema/attribute.go
  provider/schema/block.go
  provider/schema/bool_attribute.go
  provider/schema/bool_attribute_test.go
  provider/schema/doc.go
  provider/schema/float64_attribute.go
  provider/schema/float64_attribute_test.go
  provider/schema/int64_attribute.go
  provider/schema/int64_attribute_test.go
  provider/schema/list_attribute.go
  provider/schema/list_attribute_test.go
  provider/schema/list_nested_attribute.go
  provider/schema/list_nested_attribute_test.go
  provider/schema/list_nested_block.go
  provider/schema/list_nested_block_test.go
  provider/schema/map_attribute.go
  provider/schema/map_attribute_test.go
  provider/schema/map_nested_attribute.go
  provider/schema/map_nested_attribute_test.go
  provider/schema/nested_attribute.go
  provider/schema/nested_attribute_object.go
  provider/schema/nested_attribute_object_test.go
  provider/schema/nested_block_object.go
  provider/schema/nested_block_object_test.go
  provider/schema/number_attribute.go
  provider/schema/number_attribute_test.go
  provider/schema/object_attribute.go
  provider/schema/object_attribute_test.go
  provider/schema/schema.go
  provider/schema/schema_test.go
  provider/schema/set_attribute.go
  provider/schema/set_attribute_test.go
  provider/schema/set_nested_attribute.go
  provider/schema/set_nested_attribute_test.go
  provider/schema/set_nested_block.go
  provider/schema/set_nested_block_test.go
  provider/schema/single_nested_attribute.go
  provider/schema/single_nested_attribute_test.go
  provider/schema/single_nested_block.go
  provider/schema/single_nested_block_test.go
  provider/schema/string_attribute.go
  provider/schema/string_attribute_test.go
Labels: enhancement

#557 resource/schema/planmodifier: New type-specific plan modifiers package
  .changelog/557.txt
  internal/fwschema/fwxschema/attribute_plan_modification.go
  internal/fwschema/fwxschema/block_plan_modification.go
  internal/fwschema/fwxschema/nested_attribute_object_plan_modification.go
  internal/fwschema/fwxschema/nested_block_object_plan_modification.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/privatestate/data.go
  internal/privatestate/data_test.go
  internal/testing/testplanmodifier/bool.go
  internal/testing/testplanmodifier/doc.go
  internal/testing/testplanmodifier/float64.go
  internal/testing/testplanmodifier/int64.go
  internal/testing/testplanmodifier/list.go
  internal/testing/testplanmodifier/map.go
  internal/testing/testplanmodifier/number.go
  internal/testing/testplanmodifier/object.go
  internal/testing/testplanmodifier/set.go
  internal/testing/testplanmodifier/string.go
  internal/testing/testschema/attributewithboolplanmodifiers.go
  internal/testing/testschema/attributewithfloat64planmodifiers.go
  internal/testing/testschema/attributewithint64planmodifiers.go
  internal/testing/testschema/attributewithlistplanmodifiers.go
  internal/testing/testschema/attributewithmapplanmodifiers.go
  internal/testing/testschema/attributewithnumberplanmodifiers.go
  internal/testing/testschema/attributewithobjectplanmodifiers.go
  internal/testing/testschema/attributewithsetplanmodifiers.go
  internal/testing/testschema/attributewithstringplanmodifiers.go
  internal/testing/testschema/blockwithlistplanmodifiers.go
  internal/testing/testschema/blockwithobjectplanmodifiers.go
  internal/testing/testschema/blockwithsetplanmodifiers.go
  internal/testing/testschema/nested_attribute_object_with_planmodifiers.go
  internal/testing/testschema/nested_block_object_with_plan_modifiers.go
  resource/schema/planmodifier/bool.go
  resource/schema/planmodifier/describer.go
  resource/schema/planmodifier/doc.go
  resource/schema/planmodifier/float64.go
  resource/schema/planmodifier/int64.go
  resource/schema/planmodifier/list.go
  resource/schema/planmodifier/map.go
  resource/schema/planmodifier/number.go
  resource/schema/planmodifier/object.go
  resource/schema/planmodifier/set.go
  resource/schema/planmodifier/string.go
Labels: enhancement

#559 provider/schema: Fix Go documentation for Schema type
  provider/schema/schema.go
Labels: documentation

#561 Fix nesting mode for map, set and single nested attribute within data source, provider and resource schema
  datasource/schema/map_nested_attribute.go
  datasource/schema/set_nested_attribute.go
  datasource/schema/single_nested_attribute.go
  provider/schema/map_nested_attribute.go
  provider/schema/set_nested_attribute.go
  provider/schema/single_nested_attribute.go
  resource/schema/map_nested_attribute.go
  resource/schema/set_nested_attribute.go
  resource/schema/single_nested_attribute.go
Labels: bug

#564 website: Updates for tfsdk Attribute, Block, and Schema deprecations
  website/docs/plugin/framework/acctests.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/attribute-schema.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks-computed.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/force-new.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/resources/import.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/resources/plan-modification.mdx
  website/docs/plugin/framework/migrating/resources/state-upgrade.mdx
  website/docs/plugin/framework/migrating/resources/timeouts.mdx
  website/docs/plugin/framework/migrating/schema/index.mdx
  website/docs/plugin/framework/path-expressions.mdx
  website/docs/plugin/framework/paths.mdx
  website/docs/plugin/framework/providers/index.mdx
  website/docs/plugin/framework/resources/create.mdx
  website/docs/plugin/framework/resources/delete.mdx
  website/docs/plugin/framework/resources/import.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
  website/docs/plugin/framework/resources/private-state.mdx
  website/docs/plugin/framework/resources/read.mdx
  website/docs/plugin/framework/resources/state-upgrade.mdx
  website/docs/plugin/framework/resources/timeouts.mdx
  website/docs/plugin/framework/resources/update.mdx
  website/docs/plugin/framework/schemas.mdx
  website/docs/plugin/framework/validation.mdx
Labels: documentation
