Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-05, with the labels that each got.

#312 tfsdk: Remove ResourceImportStateNotImplemented() function
  .changelog/312.txt
  internal/proto6server/serve_import.go
  internal/proto6server/serve_import_test.go
  internal/proto6server/serve_resource_upgrade_state_not_implemented_test.go
  tfsdk/resource_import.go
Labels: breaking-change

#313 diag: Move (Diagnostics).ToTfprotov6Diagnostics() method to internal/toproto6 package
  .changelog/313.txt
  diag/diagnostic_test.go
  diag/diagnostics.go
  diag/diagnostics_test.go
  internal/proto6server/serve.go
  internal/proto6server/serve_import.go
  internal/toproto6/diagnostics.go
  internal/toproto6/diagnostics_test.go
Labels: breaking-change, tech-debt

#316 internal: Introduce logging unit testing
  internal/logging/context_test.go
  internal/logging/framework_test.go
  internal/proto6server/serve.go
  internal/proto6server/serve_test.go
  internal/testing/emptyprovider/provider.go
  providerserver/provider_test.go
  providerserver/providerserver_test.go
Labels: tech-debt

#311 feat: content split; local + deploy previews
  .gitignore
  Makefile
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/accessing-values.mdx
  website/docs/plugin/framework/acctests.mdx
  website/docs/plugin/framework/data-sources.mdx
  website/docs/plugin/framework/debugging.mdx
  website/docs/plugin/framework/diagnostics.mdx
  website/docs/plugin/framework/index.mdx
  website/docs/plugin/framework/providers.mdx
  website/docs/plugin/framework/resources/import.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
  website/docs/plugin/framework/resources/state-upgrade.mdx
  website/docs/plugin/framework/schemas.mdx
  website/docs/plugin/framework/types.mdx
  website/docs/plugin/framework/validation.mdx
  website/docs/plugin/framework/writing-state.mdx
  website/img/.gitkeep
  website/package-lock.json
  website/package.json
  website/scripts/website-build.sh
Labels: documentation

#319 Introduce internal/fwserver package and migrate GetProviderSchema
  internal/fromproto6/doc.go
  internal/fromproto6/getproviderschema.go
  internal/fromproto6/getproviderschema_test.go
  internal/fwserver/doc.go
  internal/fwserver/server.go
  internal/fwserver/server_getproviderschema.go
  internal/fwserver/server_getproviderschema_test.go
  internal/proto6server/serve.go
  internal/proto6server/serve_test.go
  internal/toproto6/getproviderschema.go
  internal/toproto6/getproviderschema_test.go
  internal/toproto6/schema.go
  internal/toproto6/schema_test.go
  providerserver/providerserver.go
Labels: tech-debt

#322 internal: Migrate ConfigureProvider RPC to fromproto6, fwserver, toproto6
  internal/fromproto6/configureprovider.go
  internal/fromproto6/configureprovider_test.go
  internal/fwserver/server_configureprovider.go
  internal/fwserver/server_configureprovider_test.go
  internal/proto6server/serve.go
  internal/proto6server/serve_test.go
  internal/toproto6/configureprovider.go
  internal/toproto6/configureprovider_test.go
Labels: tech-debt

#330 tfsdk: Remove Go documentation deprecation for Schema type Blocks field
  internal/fwserver/schema_validation.go
  internal/proto6server/schema_plan_modification.go
  internal/toproto6/schema.go
  tfsdk/schema.go
Labels: schema

#332 internal: ValidateDataSourceConfig RPC tidying
  internal/fwserver/server_validatedatasourceconfig.go
  internal/proto6server/serve.go
Labels: tech-debt

#333 internal/proto6server: Always use data source and resource caches, remove intermediate Provider field
  internal/proto6server/serve.go
  internal/proto6server/serve_import.go
  internal/proto6server/serve_import_test.go
  internal/proto6server/serve_test.go
  providerserver/providerserver.go
Labels: tech-debt

#336 internal: Add ProviderMeta handling to fwserver
  internal/fwserver/server.go
  internal/fwserver/server_getproviderschema.go
  internal/proto6server/serve.go
  internal/proto6server/serve_test.go
Labels: tech-debt

#337 internal: Migrate ImportResourceState RPC to fromproto6, fwserver, and toproto6
  internal/fromproto6/importresourcestate.go
  internal/fromproto6/importresourcestate_test.go
  internal/fwserver/server_importresourcestate.go
  internal/fwserver/server_importresourcestate_test.go
  internal/proto6server/serve_import.go
  internal/proto6server/serve_import_test.go
  internal/toproto6/importedresource.go
  internal/toproto6/importresourcestate.go
  internal/toproto6/state.go
  internal/toproto6/state_test.go
Labels: tech-debt

#335 Proposal: adding `IsNull()` and `IsUnknown()` methods to `attr.Value` interface
  .changelog/335.txt
  .gitignore
  .go-version
  attr/value.go
  internal/testing/types/bool.go
  internal/testing/types/number.go
  internal/testing/types/string.go
  types/bool.go
  types/bool_test.go
  types/float64.go
  types/float64_test.go
  types/int64.go
  types/int64_test.go
  types/list.go
  types/list_test.go
  types/map.go
  types/map_test.go
  types/number.go
  types/number_test.go
  types/object.go
  types/object_test.go
  types/set.go
  types/set_test.go
  types/string.go
  types/string_test.go
Labels: enhancement, breaking-change

#339 internal: Migrate ReadDataSource RPC to fromproto6, fwserver, and toproto6
  internal/fromproto6/providermeta.go
  internal/fromproto6/providermeta_test.go
  internal/fromproto6/readdatasource.go
  internal/fromproto6/readdatasource_test.go
  internal/fwserver/server_readdatasource.go
  internal/fwserver/server_readdatasource_test.go
  internal/proto6server/serve.go
  internal/toproto6/readdatasource.go
  internal/toproto6/readdatasource_test.go
Labels: tech-debt

#342 internal: Migrate ReadResource RPC to fromproto6, fwserver, and toproto6
  internal/fromproto6/readresource.go
  internal/fromproto6/readresource_test.go
  internal/fromproto6/state.go
  internal/fromproto6/state_test.go
  internal/fwserver/server_readresource.go
  internal/fwserver/server_readresource_test.go
  internal/proto6server/serve.go
  internal/toproto6/readresource.go
  internal/toproto6/readresource_test.go
Labels: tech-debt

#343 Remove unnecessary conversion to `tftypes` in `AttributePlanModifier`s implementations
  tfsdk/attribute_plan_modification.go
Labels: tech-debt

#341 internal: Migrate UpgradeResourceState RPC to fromproto6, fwserver, and toproto6
  internal/fromproto6/rawstate_test.go
  internal/fromproto6/upgraderesourcestate.go
  internal/fromproto6/upgraderesourcestate_test.go
  internal/fwserver/server_upgraderesourcestate.go
  internal/fwserver/server_upgraderesourcestate_test.go
  internal/proto6server/serve.go
  internal/toproto6/upgraderesourcestate.go
  internal/toproto6/upgraderesourcestate_test.go
  tfsdk/resource_upgrade_state.go
Labels: tech-debt

#345 internal: Migrate ApplyResourceChange RPC to fromproto6, fwserver, and toproto6
  internal/fromproto6/applyresourcechange.go
  internal/fromproto6/applyresourcechange_test.go
  internal/fromproto6/plan.go
  internal/fromproto6/plan_test.go
  internal/fwserver/server_applyresourcechange.go
  internal/fwserver/server_applyresourcechange_test.go
  internal/fwserver/server_createresource.go
  internal/fwserver/server_createresource_test.go
  internal/fwserver/server_deleteresource.go
  internal/fwserver/server_deleteresource_test.go
  internal/fwserver/server_updateresource.go
  internal/fwserver/server_updateresource_test.go
  internal/proto6/request_type.go
  internal/proto6/request_type_test.go
  internal/proto6server/serve.go
  internal/toproto6/applyresourcechange.go
  internal/toproto6/applyresourcechange_test.go
Labels: tech-debt

#347 internal/proto6server: Lift and shift RPCs into separate Go source files
  internal/proto6server/serve.go
  internal/proto6server/serve_test.go
  internal/proto6server/server_applyresourcechange.go
  internal/proto6server/server_applyresourcechange_test.go
  internal/proto6server/server_configureprovider.go
  internal/proto6server/server_configureprovider_test.go
  internal/proto6server/server_getproviderschema.go
  internal/proto6server/server_getproviderschema_test.go
  internal/proto6server/server_importresourcestate.go
  internal/proto6server/server_importresourcestate_test.go
  internal/proto6server/server_planresourcechange.go
  internal/proto6server/server_planresourcechange_test.go
  internal/proto6server/server_readdatasource.go
  internal/proto6server/server_readdatasource_test.go
  internal/proto6server/server_readresource.go
  internal/proto6server/server_readresource_test.go
  internal/proto6server/server_upgraderesourcestate.go
  internal/proto6server/server_upgraderesourcestate_test.go
  internal/proto6server/server_validatedataresourceconfig.go
  internal/proto6server/server_validatedataresourceconfig_test.go
  internal/proto6server/server_validateproviderconfig.go
  internal/proto6server/server_validateproviderconfig_test.go
  internal/proto6server/server_validateresourceconfig.go
  internal/proto6server/server_validateresourceconfig_test.go
Labels: tech-debt

#348 internal: Introduce testprovider package and implement fwserver GetProviderSchema unit testing
  internal/fwserver/server_getproviderschema_test.go
  internal/proto6server/serve_data_source_config_validators_test.go
  internal/proto6server/serve_data_source_one_test.go
  internal/proto6server/serve_data_source_two_test.go
  internal/proto6server/serve_data_source_validate_config_test.go
  internal/proto6server/serve_provider_test.go
  internal/proto6server/serve_resource_attribute_plan_modifiers_test.go
  internal/proto6server/serve_resource_config_validators_test.go
  internal/proto6server/serve_resource_import_state_not_implemented_test.go
  internal/proto6server/serve_resource_import_state_test.go
  internal/proto6server/serve_resource_one_test.go
  internal/proto6server/serve_resource_three_test.go
  internal/proto6server/serve_resource_two_test.go
  internal/proto6server/serve_resource_upgrade_state_empty_test.go
  internal/proto6server/serve_resource_upgrade_state_not_implemented_test.go
  internal/proto6server/serve_resource_upgrade_state_test.go
  internal/proto6server/serve_resource_validate_config_test.go
  internal/proto6server/server_getproviderschema_test.go
  internal/testing/testprovider/datasource.go
  internal/testing/testprovider/datasourcetype.go
  internal/testing/testprovider/provider.go
  internal/testing/testprovider/providerwithmeta.go
  internal/testing/testprovider/resource.go
  internal/testing/testprovider/resourcetype.go
Labels: tech-debt

#349 Removed `ListNestedAttributesOptions`, `SetNestedAttributesOptions` and `MapNestedAttributesOptions` types, as they were empty (no fields) and unused
  .changelog/349.txt
  internal/fwserver/attribute_validation_test.go
  internal/proto6server/serve_provider_test.go
  internal/proto6server/serve_resource_three_test.go
  internal/proto6server/serve_resource_two_test.go
  internal/toproto6/getproviderschema_test.go
  internal/toproto6/schema_attribute_test.go
  internal/toproto6/schema_test.go
  tfsdk/config_test.go
  tfsdk/nested_attributes.go
  tfsdk/plan_test.go
  tfsdk/schema_test.go
  tfsdk/state_test.go
Labels: enhancement, breaking-change

#352 internal: Implement fwserver ConfigureProvider testing and update proto6server testing
  internal/fwserver/server_configureprovider_test.go
  internal/proto6server/server_configureprovider_test.go
Labels: tech-debt

#351 .github/workflows: Remove obsolete golangci-lint-action input
  .github/workflows/ci-go.yml
Labels: github_actions

#350 New function `ValueFrom` that takes a Go value and populates a compatible `attr.Value`, given a descriptive `attr.Type`
  .changelog/350.txt
  tfsdk/value_as.go
  tfsdk/value_from.go
  tfsdk/value_from_test.go
Labels: enhancement, types, reflection

#354 Prevent `ToTerraformValue` panic when the underlying `attr.Value` types doesn't have type information for its fields
  .changelog/354.txt
  types/list.go
  types/list_test.go
  types/map.go
  types/map_test.go
  types/object.go
  types/object_test.go
  types/set.go
  types/set_test.go
Labels: bug, types
