Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-04, with the labels that each got.

#228 docs/design: Upgrade Resource State
  docs/design/upgrade-resource-state.md
Labels: design-doc, sdkv2-parity

#294 tfsdk: Introduce new ProviderServer functions, deprecate existing
  .changelog/pending.txt
  tfsdk/serve.go
  tfsdk/serve_test.go
Labels: enhancement

#292 tfsdk: Initial ResourceWithUpgradeState implementation
  .changelog/292.txt
  README.md
  tfsdk/resource_upgrade_state.go
  tfsdk/serve.go
  tfsdk/serve_provider_test.go
  tfsdk/serve_resource_upgrade_state_empty_test.go
  tfsdk/serve_resource_upgrade_state_not_implemented_test.go
  tfsdk/serve_resource_upgrade_state_test.go
  tfsdk/serve_test.go
Labels: enhancement, sdkv2-parity

#301 tfsdk: Added automatic RemoveResource() call after Resource type Delete method execution
  .changelog/301.txt
  tfsdk/resource.go
  tfsdk/serve.go
  tfsdk/serve_test.go
  tfsdk/state.go
Labels: enhancement

#296 tfsdk: Introduce ServeOpts Address field, deprecate Name field
  .changelog/296.txt
  tfsdk/serve.go
  tfsdk/serve_opts.go
  tfsdk/serve_opts_test.go
Labels: enhancement

#303 correct NewProtocol6ProviderServerWithError to match the sdkv2 defini…
  .changelog/303.txt
  tfsdk/serve.go
  tfsdk/serve_test.go
Labels: bug

#297 tfsdk: Move Resource ImportState method to optional ResourceWithImportState interface
  .changelog/297.txt
  tfsdk/resource.go
  tfsdk/resource_import.go
  tfsdk/serve_import.go
  tfsdk/serve_import_test.go
  tfsdk/serve_provider_test.go
  tfsdk/serve_resource_attribute_plan_modifiers_test.go
  tfsdk/serve_resource_config_validators_test.go
  tfsdk/serve_resource_import_state_not_implemented_test.go
  tfsdk/serve_resource_one_test.go
  tfsdk/serve_resource_three_test.go
  tfsdk/serve_resource_two_test.go
  tfsdk/serve_resource_upgrade_state_empty_test.go
  tfsdk/serve_resource_upgrade_state_test.go
  tfsdk/serve_resource_validate_config_test.go
  tfsdk/serve_test.go
Labels: enhancement

#300 tfsdk: Added logging for all framework handoffs to provider defined logic
  .changelog/300.txt
  internal/logging/framework.go
  internal/logging/keys.go
  tfsdk/attribute.go
  tfsdk/attribute_plan_modification.go
  tfsdk/config.go
  tfsdk/plan.go
  tfsdk/serve.go
  tfsdk/serve_import.go
  tfsdk/state.go
Labels: enhancement
