Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-08, with the labels that each got.

#431 website: Add Resource Destroy Plan Diagnostics section
  tfsdk/request.go
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
Labels: documentation

#434 tfsdk: Migrate `RequiresReplace()`, `RequiresReplaceIf()`, and `UseStateForUnknown()` plan modifier functions to the `resource` package
  .changelog/434.txt
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification_test.go
  resource/plan_modifiers.go
  resource/plan_modifiers_test.go
  tfsdk/attribute_plan_modification.go
  website/docs/plugin/framework/resources/plan-modification.mdx
Labels: breaking-change, tech-debt

#436 all: Go package documentation updates post datasource, provider, and resource package migration
  datasource/data_source.go
  datasource/doc.go
  provider/doc.go
  provider/provider.go
  providerserver/doc.go
  resource/doc.go
  resource/resource.go
Labels: documentation

#439 all: Run Go 1.19 fmt
  datasource/data_source.go
  internal/fromproto5/providermeta.go
  internal/fromproto6/providermeta.go
  path/expression.go
  path/path.go
  provider/provider.go
  providerserver/serve_opts.go
  resource/resource.go
Labels: tech-debt

#440 tfsdk: Additional preparations for multiple schema implementations
  .changelog/440.txt
  internal/fromproto5/config.go
  internal/fromproto5/importresourcestate.go
  internal/fromproto5/importresourcestate_test.go
  internal/fromproto5/plan.go
  internal/fromproto5/providermeta.go
  internal/fromproto5/state.go
  internal/fromproto6/config.go
  internal/fromproto6/importresourcestate.go
  internal/fromproto6/importresourcestate_test.go
  internal/fromproto6/plan.go
  internal/fromproto6/providermeta.go
  internal/fromproto6/state.go
  internal/fromtftypes/attribute_path.go
  internal/fromtftypes/attribute_path_test.go
  internal/fwschema/attribute.go
  internal/fwschema/nested_attributes.go
  internal/fwschema/nested_attributes_test.go
  internal/fwschema/schema.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/config.go
  internal/fwserver/plan.go
  internal/fwserver/server_createresource.go
  internal/fwserver/server_deleteresource.go
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_planresourcechange_test.go
  internal/fwserver/server_updateresource.go
  internal/fwserver/server_upgraderesourcestate.go
  internal/fwserver/server_upgraderesourcestate_test.go
  internal/fwserver/state.go
  internal/proto5server/server_upgraderesourcestate_test.go
  internal/proto6server/server_upgraderesourcestate_test.go
  internal/toproto5/config.go
  internal/toproto5/state.go
  internal/toproto6/config.go
  internal/toproto6/state.go
  resource/plan_modifiers.go
  resource/plan_modifiers_test.go
  tfsdk/attribute.go
  tfsdk/attribute_test.go
  tfsdk/block.go
  tfsdk/block_test.go
  tfsdk/config.go
  tfsdk/path_matches.go
  tfsdk/path_matches_test.go
  tfsdk/plan.go
  tfsdk/schema.go
  tfsdk/schema_test.go
  tfsdk/state.go
Labels: tech-debt

#443 tfsdk: Clarify Attribute type DeprecationMessage documentation for Terraform 1.2.7 and later
  tfsdk/attribute.go
  website/docs/plugin/framework/schemas.mdx
Labels: documentation

#445 all: Bump Go Version to 1.18
  .changelog/445.txt
  .github/workflows/ci-go.yml
  .golangci.yml
  README.md
  go.mod
  go.sum
Labels: tech-debt

#452 internal/privatestate: Handle terraform-plugin-sdk private state in NewData
  .changelog/452.txt
  internal/privatestate/data.go
  internal/privatestate/data_test.go
Labels: bug

#451 internal/fwschemadata: Initial package
  internal/fwschemadata/data.go
  internal/fwschemadata/data_get.go
  internal/fwschemadata/data_get_test.go
  internal/fwschemadata/data_path_exists.go
  internal/fwschemadata/data_path_exists_test.go
  internal/fwschemadata/data_path_matches.go
  internal/fwschemadata/data_path_matches_test.go
  internal/fwschemadata/data_terraform_value.go
  internal/fwschemadata/doc.go
  internal/fwschemadata/pointer_test.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: tech-debt

#453 internal/fwschemadata: Migrate tfsdk GetAttribute and getAttributeValue logic
  internal/fwschemadata/data_get_at_path.go
  internal/fwschemadata/data_get_at_path_test.go
  internal/fwschemadata/data_value.go
  internal/fwschemadata/data_value_test.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: tech-debt

#454 internal/fwschemadata: Migrate tfsdk Set and SetAttribute logic
  internal/fwschemadata/data_set.go
  internal/fwschemadata/data_set_at_path.go
  internal/fwschemadata/data_set_at_path_test.go
  internal/fwschemadata/data_set_test.go
  internal/fwschemadata/tftypes_value.go
  internal/fwschemadata/tftypes_value_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
  tfsdk/tftypes_transform.go
Labels: tech-debt

#450 tfsdk: Handle Schema type deprecations
  .changelog/450.txt
  internal/fwschema/schema.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/server_planresourcechange_test.go
  tfsdk/schema.go
  tfsdk/schema_test.go
Labels: breaking-change, tech-debt

#464 internal/fwschemadata: Replace fwserver duplicate logic, add data description
  internal/fwschemadata/data.go
  internal/fwschemadata/data_description.go
  internal/fwschemadata/data_get_at_path.go
  internal/fwschemadata/data_path_exists.go
  internal/fwschemadata/data_set.go
  internal/fwschemadata/data_set_at_path.go
  internal/fwschemadata/data_value.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_validation.go
  internal/fwserver/config.go
  internal/fwserver/plan.go
  internal/fwserver/state.go
  tfsdk/config.go
  tfsdk/plan.go
  tfsdk/state.go
Labels: tech-debt

#458 Adding website documentation for private state management
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/resources/private-state.mdx
Labels: documentation
