Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-09, with the labels that each got.

#465 internal/fwserver: Delay deprecated attribute/block warnings for unknown values
  .changelog/465.txt
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/block_validation.go
  internal/fwserver/block_validation_test.go
Labels: bug

#468 internal/fwserver: Use existing data instead of path-based lookups during plan modification
  .changelog/468.txt
  internal/fwserver/attr_value.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/schema_plan_modification.go
  internal/fwserver/schema_plan_modification_test.go
Labels: bug

#475 internal/fwserver: Prevent two sources of errors/panics
  internal/fwschemadata/data_value.go
  internal/fwschemadata/data_value_test.go
  internal/fwserver/attr_value.go
  internal/fwserver/block_plan_modification_test.go
Labels: bug

#477 tfsdk: Add support for single nested mode blocks
  .changelog/477.txt
  internal/fwschema/block_nested_mode.go
  internal/fwschemadata/data_get_at_path_test.go
  internal/fwschemadata/data_get_test.go
  internal/fwschemadata/data_value_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/block_validation.go
  internal/fwserver/block_validation_test.go
  internal/toproto5/block.go
  internal/toproto5/block_test.go
  internal/toproto5/getproviderschema_test.go
  internal/toproto5/schema_test.go
  internal/toproto6/block.go
  internal/toproto6/block_test.go
  internal/toproto6/getproviderschema_test.go
  internal/toproto6/schema_test.go
  tfsdk/block.go
  tfsdk/block_nested_mode.go
  tfsdk/block_test.go
  tfsdk/schema_test.go
  website/docs/plugin/framework/paths.mdx
Labels: enhancement

#478 provider: Remove DataSourceType and ResourceType types, Provider GetDataSources and GetResources methods
  .changelog/478.txt
  datasource/data_source.go
  internal/fwserver/server.go
  internal/fwserver/server_getproviderschema_test.go
  internal/fwserver/server_upgraderesourcestate_test.go
  internal/fwserver/server_validatedatasourceconfig_test.go
  internal/fwserver/server_validateresourceconfig_test.go
  internal/proto5server/server_applyresourcechange_test.go
  internal/proto5server/server_getproviderschema_test.go
  internal/proto5server/server_importresourcestate_test.go
  internal/proto5server/server_planresourcechange_test.go
  internal/proto5server/server_readdatasource_test.go
  internal/proto5server/server_readresource_test.go
  internal/proto5server/server_upgraderesourcestate_test.go
  internal/proto5server/server_validatedatasourceconfig_test.go
  internal/proto5server/server_validateresourcetypeconfig_test.go
  internal/proto6server/server_applyresourcechange_test.go
  internal/proto6server/server_getproviderschema_test.go
  internal/proto6server/server_importresourcestate_test.go
  internal/proto6server/server_planresourcechange_test.go
  internal/proto6server/server_readdatasource_test.go
  internal/proto6server/server_readresource_test.go
  internal/proto6server/server_upgraderesourcestate_test.go
  internal/proto6server/server_validatedataresourceconfig_test.go
  internal/proto6server/server_validateresourceconfig_test.go
  internal/testing/testprovider/datasource.go
  internal/testing/testprovider/datasourcetype.go
  internal/testing/testprovider/datasourcewithgetschema.go
  internal/testing/testprovider/datasourcewithgetschema_temp.go
  internal/testing/testprovider/datasourcewithmetadata.go
  internal/testing/testprovider/provider.go
  internal/testing/testprovider/providerwithgetdatasources.go
  internal/testing/testprovider/providerwithgetresources.go
  internal/testing/testprovider/resource.go
  internal/testing/testprovider/resourcetype.go
  internal/testing/testprovider/resourcewithgetschema.go
  internal/testing/testprovider/resourcewithgetschema_temp.go
  internal/testing/testprovider/resourcewithmetadata.go
  provider/data_source_type.go
  provider/provider.go
  provider/resource_type.go
  resource/resource.go
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/resources/index.mdx
Labels: breaking-change

#473 website: Migration guide updates for provider.DataSourceType and provider.ResourceType deprecation
  website/docs/plugin/framework/migrating/attributes-blocks/attribute-schema.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/force-new.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx
  website/docs/plugin/framework/migrating/data-sources/index.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/resources/crud.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/schema/index.mdx
Labels: documentation

#482 [docs] Typo in resources index: s/Read/Delete/
  website/docs/plugin/framework/resources/index.mdx
Labels: documentation

#484 docs: Additional migration notes on Update handling and RemoveResource handling
  website/docs/plugin/framework/migrating/resources/crud.mdx
Labels: documentation

#481 Add Validate() to all collections
  .changelog/481.txt
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/schema_plan_modification_test.go
  internal/reflect/map.go
  types/list.go
  types/list_test.go
  types/map.go
  types/map_test.go
  types/set.go
  types/set_test.go
Labels: bug

#494 Replace deprecated linters with unused
  .golangci.yml
Labels: tech-debt

#487 Update docs to include timeouts
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/data-sources/index.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/resources/timeouts.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/timeouts.mdx
Labels: documentation

#495 Improve diagnostics when types that cannot handle unknown or null are used
  internal/fwschemadata/data_get.go
  internal/fwschemadata/data_get_at_path.go
  internal/fwschemadata/data_get_at_path_test.go
  internal/fwschemadata/data_get_test.go
  internal/reflect/build_value_test.go
  internal/reflect/into.go
  tfsdk/value_as.go
  types/list.go
  types/map.go
  types/object.go
  types/set.go
Labels: tech-debt, reflection

#497 attr: Add ValueType method to Type interface
  .changelog/497.txt
  attr/type.go
  internal/fwschemadata/data_get_at_path_test.go
  internal/fwschemadata/data_get_test.go
  internal/reflect/build_value_test.go
  internal/reflect/into.go
  internal/testing/types/bool.go
  internal/testing/types/invalid.go
  internal/testing/types/number.go
  internal/testing/types/string.go
  types/list.go
  types/map.go
  types/object.go
  types/primitive.go
  types/primitive_test.go
  types/set.go
Labels: enhancement, breaking-change, types

#500 website: Add beta callout on all pages
  website/docs/plugin/framework/accessing-values.mdx
  website/docs/plugin/framework/acctests.mdx
  website/docs/plugin/framework/data-sources/configure.mdx
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/data-sources/timeouts.mdx
  website/docs/plugin/framework/debugging.mdx
  website/docs/plugin/framework/diagnostics.mdx
  website/docs/plugin/framework/index.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/attribute-schema.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks-computed.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/force-new.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx
  website/docs/plugin/framework/migrating/data-sources/index.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/index.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/resources/crud.mdx
  website/docs/plugin/framework/migrating/resources/import.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/resources/plan-modification.mdx
  website/docs/plugin/framework/migrating/resources/state-upgrade.mdx
  website/docs/plugin/framework/migrating/resources/timeouts.mdx
  website/docs/plugin/framework/migrating/schema/index.mdx
  website/docs/plugin/framework/migrating/testing.mdx
  website/docs/plugin/framework/path-expressions.mdx
  website/docs/plugin/framework/paths.mdx
  website/docs/plugin/framework/provider-servers.mdx
  website/docs/plugin/framework/providers.mdx
  website/docs/plugin/framework/resources/configure.mdx
  website/docs/plugin/framework/resources/import.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
  website/docs/plugin/framework/resources/private-state.mdx
  website/docs/plugin/framework/resources/state-upgrade.mdx
  website/docs/plugin/framework/resources/timeouts.mdx
  website/docs/plugin/framework/schemas.mdx
  website/docs/plugin/framework/types.mdx
  website/docs/plugin/framework/validation.mdx
  website/docs/plugin/framework/writing-state.mdx
Labels: documentation

#501 website: Create concept-specific configuration validation pages
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/data-sources/validate-configuration.mdx
  website/docs/plugin/framework/providers/index.mdx
  website/docs/plugin/framework/providers/validate-configuration.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/validate-configuration.mdx
  website/docs/plugin/framework/validation.mdx
Labels: documentation
