Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-06, with the labels that each got.

#359 internal: Implement fwserver ReadDataSource testing and update proto6server testing
  internal/fromproto6/readdatasource.go
  internal/fromproto6/readdatasource_test.go
  internal/fwserver/server_readdatasource.go
  internal/fwserver/server_readdatasource_test.go
  internal/proto6server/serve_data_source_one_test.go
  internal/proto6server/serve_data_source_two_test.go
  internal/proto6server/serve_provider_test.go
  internal/proto6server/server_readdatasource_test.go
  internal/testing/testprovider/datasource.go
Labels: tech-debt

#360 internal: Implement fwserver ReadResource testing and update proto6server testing
  internal/fwserver/server_readresource_test.go
  internal/proto6server/server_readresource_test.go
  internal/testing/testprovider/resource.go
Labels: tech-debt

#361 internal: Implement fwserver ImportResourceState testing and update proto6server testing
  internal/fwserver/server_importresourcestate_test.go
  internal/proto6server/serve_provider_test.go
  internal/proto6server/serve_resource_import_state_not_implemented_test.go
  internal/proto6server/serve_resource_import_state_test.go
  internal/proto6server/server_importresourcestate_test.go
  internal/testing/testprovider/resourcewithimportstate.go
Labels: tech-debt

#362 internal: Implement fwserver ApplyResourceChange testing and update proto6server testing
  internal/fwserver/server_applyresourcechange_test.go
  internal/fwserver/server_createresource_test.go
  internal/fwserver/server_deleteresource_test.go
  internal/fwserver/server_updateresource_test.go
  internal/proto6server/server_applyresourcechange_test.go
Labels: tech-debt

#367 internal: Implement fwserver PlanResourceChange testing and update proto6server testing
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_validation.go
  internal/fwserver/config.go
  internal/fwserver/plan.go
  internal/fwserver/schema.go
  internal/fwserver/schema_plan_modification.go
  internal/fwserver/schema_validation.go
  internal/fwserver/server_planresourcechange_test.go
  internal/fwserver/state.go
  internal/proto6server/serve_provider_test.go
  internal/proto6server/serve_resource_attribute_plan_modifiers_test.go
  internal/proto6server/serve_resource_one_test.go
  internal/proto6server/serve_resource_three_test.go
  internal/proto6server/serve_resource_two_test.go
  internal/proto6server/server_planresourcechange_test.go
  internal/testing/emptyprovider/provider.go
  internal/testing/testprovider/attributeplanmodifier.go
  internal/testing/testprovider/resourcewithmodifyplan.go
  providerserver/providerserver_test.go
Labels: tech-debt

#370 internal/fwserver: Add Attribute validation for missing required and invalid read-only configurations
  .changelog/370.txt
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
Labels: enhancement

#371 tfsdk: Prevent configuration handling error when Schema contains Blocks
  .changelog/371.txt
  tfsdk/attribute_test.go
  tfsdk/block.go
  tfsdk/block_test.go
Labels: bug

#374 Update README and CI to reflect 1.17 and 1.18 support
  .github/workflows/ci-go.yml
  README.md
Labels: documentation

#379 tfsdk: Augment Provider interface GetDataSources and GetResources method Go documentation
  tfsdk/provider.go
Labels: documentation

#376 Add `.String()` method to `attr.Value` interface
  .changelog/376.txt
  attr/value.go
  internal/reflect/pointer_test.go
  internal/reflect/primitive_test.go
  internal/testing/types/bool.go
  internal/testing/types/string.go
  tfsdk/config_test.go
  tfsdk/convert_test.go
  tfsdk/plan_test.go
  tfsdk/state_test.go
  types/bool.go
  types/bool_test.go
  types/float64.go
  types/float64_test.go
  types/int64.go
  types/int64_test.go
  types/list.go
  types/list_test.go
  types/map.go
  types/map_test.go
  types/number.go
  types/number_test.go
  types/object.go
  types/object_test.go
  types/set.go
  types/set_test.go
  types/string.go
  types/string_test.go
Labels: enhancement, breaking-change, types

#378 website: Add Provider Servers page and adjust content for protocol version 5 support
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/acctests.mdx
  website/docs/plugin/framework/debugging.mdx
  website/docs/plugin/framework/index.mdx
  website/docs/plugin/framework/provider-servers.mdx
  website/docs/plugin/framework/providers.mdx
Labels: documentation

#383 tfsdk: Clarify NestingMode requirement in Block Go documentation
  tfsdk/block.go
Labels: documentation

#385 .github/workflows: Add terraform-provider-corner testing for tfprotov5
  .github/workflows/ci-go.yml
Labels: enhancement

#386 tfsdk: Add missing Resource interface declaration in ResourceWithImportState and ResourceWithUpgradeState
  tfsdk/resource_import.go
  tfsdk/resource_upgrade_state.go
Labels: tech-debt

#392 Add convenience functions for `ErrorsCount`, `WarningsCount`, `Errors` and`Warnings`
  .changelog/392.txt
  diag/diagnostics.go
  diag/diagnostics_test.go
Labels: enhancement

#394 all: Add missing package-level Go documentation
  diag/doc.go
  internal/logging/doc.go
  internal/reflect/doc.go
  internal/testing/doc.go
  internal/testing/planmodifiers/doc.go
  internal/testing/testprovider/doc.go
  path/doc.go
  providerserver/doc.go
  tfsdk/doc.go
  types/doc.go
Labels: documentation

#396 path: Initial Path Expression Support
  .changelog/396.txt
  internal/fromtftypes/attribute_path_step.go
  internal/fromtftypes/attribute_path_step_test.go
  internal/fromtftypes/doc.go
  internal/fromtftypes/value.go
  internal/fromtftypes/value_test.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/block_validation.go
  internal/fwserver/schema_validation.go
  path/expression.go
  path/expression_step.go
  path/expression_step_attribute_name_exact.go
  path/expression_step_attribute_name_exact_test.go
  path/expression_step_element_key_int_any.go
  path/expression_step_element_key_int_any_test.go
  path/expression_step_element_key_int_exact.go
  path/expression_step_element_key_int_exact_test.go
  path/expression_step_element_key_string_any.go
  path/expression_step_element_key_string_any_test.go
  path/expression_step_element_key_string_exact.go
  path/expression_step_element_key_string_exact_test.go
  path/expression_step_element_key_value_any.go
  path/expression_step_element_key_value_any_test.go
  path/expression_step_element_key_value_exact.go
  path/expression_step_element_key_value_exact_test.go
  path/expression_step_parent.go
  path/expression_step_parent_test.go
  path/expression_steps.go
  path/expression_steps_test.go
  path/expression_test.go
  path/expressions.go
  path/expressions_test.go
  path/path.go
  path/path_step.go
  path/path_step_attribute_name.go
  path/path_step_attribute_name_test.go
  path/path_step_element_key_int.go
  path/path_step_element_key_int_test.go
  path/path_step_element_key_string.go
  path/path_step_element_key_string_test.go
  path/path_step_element_key_value.go
  path/path_step_element_key_value_test.go
  path/path_steps.go
  path/path_steps_test.go
  path/path_test.go
  tfsdk/attribute_plan_modification.go
  tfsdk/attribute_validation.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/path_matches.go
  tfsdk/path_matches_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
  tfsdk/tftypes_attribute_path.go
  tfsdk/tftypes_attribute_path_test.go
Labels: enhancement
