Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-07, with the labels that each got.

#401 path: Add Append methods for Paths and Expressions
  path/expressions.go
  path/expressions_test.go
  path/paths.go
  path/paths_test.go
Labels: enhancement

#409 Support plan modifiers returning warning and error diagnostics on resource destruction with Terraform 1.3 and later
  .changelog/409.txt
  internal/fwserver/server_capabilities.go
  internal/fwserver/server_getproviderschema.go
  internal/fwserver/server_getproviderschema_test.go
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_planresourcechange_test.go
  internal/proto5server/server_getproviderschema_test.go
  internal/proto5server/server_planresourcechange_test.go
  internal/proto6server/server_getproviderschema_test.go
  internal/proto6server/server_planresourcechange_test.go
  internal/toproto5/getproviderschema.go
  internal/toproto5/server_capabilities.go
  internal/toproto5/server_capabilities_test.go
  internal/toproto6/getproviderschema.go
  internal/toproto6/server_capabilities.go
  internal/toproto6/server_capabilities_test.go
  website/docs/plugin/framework/resources/plan-modification.mdx
Labels: enhancement, breaking-change

#410 tfsdk: Ensure Config, Plan, and State PathMatches will return null and unknown parent paths
  path/expression.go
  path/expression_steps.go
  path/expression_steps_test.go
  path/expression_test.go
  tfsdk/config.go
  tfsdk/config_test.go
  tfsdk/path_matches.go
  tfsdk/path_matches_test.go
  tfsdk/plan.go
  tfsdk/plan_test.go
  tfsdk/state.go
  tfsdk/state_test.go
Labels: bug

#413 path+website: Additional Go documentation and initial website documentation for paths and path expressions
  path/expression.go
  path/expressions.go
  path/path.go
  path/paths.go
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/path-expressions.mdx
  website/docs/plugin/framework/paths.mdx
  website/docs/plugin/framework/validation.mdx
Labels: documentation

#420 path: Ensure Expression root flag is appropriately set and checked
  .changelog/420.txt
  path/expression.go
  path/path.go
Labels: bug, schema

#423 chore: readme & contributing
  .github/CONTRIBUTING.md
  website/README.md
Labels: documentation

#424 Update docs to reflect breaking changes in v0.10.0 for path.Path
  website/docs/plugin/framework/resources/import.mdx
  website/docs/plugin/framework/resources/state-upgrade.mdx
Labels: documentation

#422 internal/fwserver: Implement Block MaxItems/MinItems validation for Terraform 0.12 through 0.15.1
  .changelog/422.txt
  internal/fwserver/block_validation.go
  internal/fwserver/block_validation_test.go
Labels: enhancement, sdkv2-parity, schema

#426 Using UnmarshalWithOpts in order to ignore undefined attributes
  .changelog/426.txt
  go.mod
  go.sum
  internal/fwserver/server_upgraderesourcestate.go
  internal/fwserver/server_upgraderesourcestate_test.go
Labels: bug

#429 tfsdk: Clarify Attribute and Block type DeprecationMessage field usage
  tfsdk/attribute.go
  tfsdk/block.go
  website/docs/plugin/framework/schemas.mdx
Labels: documentation
