Repository hashicorp/terraform-plugin-framework, pull requests merged in 2022-12, with the labels that each got.

#548 Fix Framework allows top-level schema attributes that conflict with Terraform meta-arguments
  .changelog/548.txt
  datasource/schema/schema.go
  datasource/schema/schema_test.go
  internal/fwschema/schema.go
  internal/fwserver/server.go
  internal/fwserver/server_getproviderschema_test.go
  provider/metaschema/schema.go
  provider/metaschema/schema_test.go
  provider/schema/schema.go
  provider/schema/schema_test.go
  resource/schema/schema.go
  resource/schema/schema_test.go
Labels: bug

#576 resource+tfsdk: Remove tfsdk package schema types and functions
  .changelog/576.txt
  .golangci.yml
  datasource/data_source.go
  internal/fwschema/attribute_nesting_mode.go
  internal/fwschema/fwxschema/attribute_plan_modification.go
  internal/fwschema/fwxschema/attribute_validation.go
  internal/fwschema/fwxschema/block_plan_modification.go
  internal/fwschema/fwxschema/block_validation.go
  internal/fwschema/nested_attributes.go
  internal/fwschema/nested_attributes_test.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/attribute_validation.go
  internal/fwserver/attribute_validation_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/block_validation.go
  internal/fwserver/block_validation_test.go
  internal/fwserver/schema_plan_modification.go
  internal/fwserver/schema_validation.go
  internal/fwserver/server.go
  internal/testing/planmodifiers/planmodifiers.go
  internal/testing/testprovider/attributeplanmodifier.go
  internal/testing/testprovider/attributevalidator.go
  internal/testing/types/listnestedattributescustom.go
  internal/testing/types/mapnestedattributescustom.go
  internal/testing/types/setnestedattributescustom.go
  internal/testing/types/singlenestedattributescustom.go
  internal/toproto5/schema_attribute.go
  internal/toproto6/block_test.go
  internal/toproto6/schema_attribute.go
  provider/provider.go
  resource/plan_modifiers.go
  resource/plan_modifiers_test.go
  resource/resource.go
  tfsdk/attribute.go
  tfsdk/attribute_plan_modification.go
  tfsdk/attribute_test.go
  tfsdk/attribute_validation.go
  tfsdk/block.go
  tfsdk/block_nested_mode.go
  tfsdk/block_test.go
  tfsdk/config_test.go
  tfsdk/nested_attribute_object.go
  tfsdk/nested_attributes.go
  tfsdk/nested_block_object.go
  tfsdk/plan_test.go
  tfsdk/pointer_test.go
  tfsdk/schema.go
  tfsdk/schema_test.go
  tfsdk/state_test.go
Labels: breaking-change

#554 Refactor Schema and Schema Data Related Documentation
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/getting-started/code-walkthrough.mdx
  website/docs/plugin/framework/handling-data/accessing-values.mdx
  website/docs/plugin/framework/handling-data/attributes.mdx
  website/docs/plugin/framework/handling-data/blocks.mdx
  website/docs/plugin/framework/handling-data/conversion-rules.mdx
  website/docs/plugin/framework/handling-data/path-expressions.mdx
  website/docs/plugin/framework/handling-data/paths.mdx
  website/docs/plugin/framework/handling-data/schemas.mdx
  website/docs/plugin/framework/handling-data/terraform-concepts.mdx
  website/docs/plugin/framework/handling-data/writing-state.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/attribute-schema.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks-computed.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/force-new.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx
  website/docs/plugin/framework/migrating/data-sources/index.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/resources/crud.mdx
  website/docs/plugin/framework/migrating/resources/import.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/resources/plan-modification.mdx
  website/docs/plugin/framework/migrating/resources/state-upgrade.mdx
  website/docs/plugin/framework/migrating/schema/index.mdx
  website/docs/plugin/framework/migrating/testing.mdx
  website/docs/plugin/framework/writing-state.mdx
Labels: documentation

#580 provider: Require Metadata method for Provider interface
  .changelog/580.txt
  internal/fwserver/server_getproviderschema.go
  internal/fwserver/server_getproviderschema_test.go
  internal/proto5server/server_getproviderschema_test.go
  internal/proto6server/server_getproviderschema_test.go
  internal/testing/testprovider/provider.go
  internal/testing/testprovider/providerwithmetadata.go
  provider/provider.go
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/providers/index.mdx
  website/docs/plugin/framework/resources/index.mdx
Labels: breaking-change

#578 Remove beta verbiage and state compatibility promises
  .changelog/578.txt
  README.md
  website/docs/plugin/framework/acctests.mdx
  website/docs/plugin/framework/data-sources/configure.mdx
  website/docs/plugin/framework/data-sources/index.mdx
  website/docs/plugin/framework/data-sources/timeouts.mdx
  website/docs/plugin/framework/data-sources/validate-configuration.mdx
  website/docs/plugin/framework/debugging.mdx
  website/docs/plugin/framework/diagnostics.mdx
  website/docs/plugin/framework/handling-data/accessing-values.mdx
  website/docs/plugin/framework/handling-data/attributes.mdx
  website/docs/plugin/framework/handling-data/path-expressions.mdx
  website/docs/plugin/framework/handling-data/paths.mdx
  website/docs/plugin/framework/handling-data/schemas.mdx
  website/docs/plugin/framework/handling-data/writing-state.mdx
  website/docs/plugin/framework/index.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/attribute-schema.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks-computed.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/blocks.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/force-new.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-custom.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/validators-predefined.mdx
  website/docs/plugin/framework/migrating/data-sources/index.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/index.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/resources/crud.mdx
  website/docs/plugin/framework/migrating/resources/import.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
  website/docs/plugin/framework/migrating/resources/plan-modification.mdx
  website/docs/plugin/framework/migrating/resources/state-upgrade.mdx
  website/docs/plugin/framework/migrating/resources/timeouts.mdx
  website/docs/plugin/framework/migrating/schema/index.mdx
  website/docs/plugin/framework/migrating/testing.mdx
  website/docs/plugin/framework/provider-servers.mdx
  website/docs/plugin/framework/providers/index.mdx
  website/docs/plugin/framework/providers/validate-configuration.mdx
  website/docs/plugin/framework/resources/configure.mdx
  website/docs/plugin/framework/resources/create.mdx
  website/docs/plugin/framework/resources/delete.mdx
  website/docs/plugin/framework/resources/import.mdx
  website/docs/plugin/framework/resources/index.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
  website/docs/plugin/framework/resources/private-state.mdx
  website/docs/plugin/framework/resources/read.mdx
  website/docs/plugin/framework/resources/state-upgrade.mdx
  website/docs/plugin/framework/resources/timeouts.mdx
  website/docs/plugin/framework/resources/update.mdx
  website/docs/plugin/framework/resources/validate-configuration.mdx
  website/docs/plugin/framework/validation.mdx
Labels: documentation

#584 Improvements to Documentation
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/getting-started/code-walkthrough.mdx
  website/docs/plugin/framework/handling-data/attributes.mdx
  website/docs/plugin/framework/handling-data/blocks.mdx
  website/docs/plugin/framework/handling-data/custom-types.mdx
  website/docs/plugin/framework/handling-data/schemas.mdx
  website/docs/plugin/framework/handling-data/terraform-concepts.mdx
Labels: documentation, enhancement

#586 website: Further clarify configuration validation and when API access is available
  website/docs/plugin/framework/data-sources/validate-configuration.mdx
  website/docs/plugin/framework/providers/validate-configuration.mdx
  website/docs/plugin/framework/resources/plan-modification.mdx
  website/docs/plugin/framework/resources/validate-configuration.mdx
Labels: documentation

#591 types: Ensure List/Map/Object/Set Attributes/AttributeTypes/Elements returns cannot mutate underlying data
  .changelog/591.txt
  internal/fwserver/attribute_plan_modification_test.go
  types/basetypes/list.go
  types/basetypes/list_test.go
  types/basetypes/map.go
  types/basetypes/map_test.go
  types/basetypes/object.go
  types/basetypes/object_test.go
  types/basetypes/set.go
  types/basetypes/set_test.go
Labels: bug

#598 website: Point overview muxing link at migration guide content
  website/docs/plugin/framework/migrating/index.mdx
Labels: documentation

#602 tfsdk+types: Fix ObjectType missing attribute error and PathMatches schema validation
  .changelog/602.txt
  datasource/schema/object_attribute_test.go
  internal/fwschemadata/data_path_matches.go
  internal/fwschemadata/data_path_matches_test.go
  internal/fwschemadata/data_valid_path_expression.go
  internal/fwschemadata/data_valid_path_expression_test.go
  provider/metaschema/object_attribute_test.go
  provider/schema/object_attribute_test.go
  resource/schema/object_attribute_test.go
  tfsdk/config_test.go
  tfsdk/plan_test.go
  types/basetypes/object.go
Labels: bug
