Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-01, with the labels that each got.

#604 all: Convert empty list and set block values to null
  .changelog/604.txt
  internal/fromproto5/config.go
  internal/fromproto5/config_test.go
  internal/fromproto5/dynamic_value.go
  internal/fromproto5/dynamic_value_test.go
  internal/fromproto5/plan.go
  internal/fromproto5/plan_test.go
  internal/fromproto5/state.go
  internal/fromproto5/state_test.go
  internal/fromproto6/config.go
  internal/fromproto6/config_test.go
  internal/fromproto6/dynamic_value.go
  internal/fromproto6/dynamic_value_test.go
  internal/fromproto6/plan.go
  internal/fromproto6/plan_test.go
  internal/fromproto6/state.go
  internal/fromproto6/state_test.go
  internal/fwschema/block.go
  internal/fwschema/schema.go
  internal/fwschema/schema_test.go
  internal/fwschemadata/data_nullify_collection_blocks.go
  internal/fwschemadata/data_nullify_collection_blocks_test.go
  path/expressions.go
  path/expressions_test.go
Labels: enhancement, sdkv2-parity

#610 ci: Enable paralleltest linter
  .golangci.yml
  datasource/schema/schema_test.go
  diag/diagnostics_test.go
  internal/privatestate/data_test.go
  internal/reflect/struct_test.go
  provider/metaschema/schema_test.go
  provider/schema/schema_test.go
  providerserver/providerserver_test.go
  resource/schema/schema_test.go
  types/basetypes/list_test.go
  types/basetypes/map_test.go
Labels: tech-debt

#614 types/basetypes: Fixed Float64Type validation to handle valid, stringified numbers from Terraform
  .changelog/614.txt
  types/basetypes/float64_test.go
  types/basetypes/float64_type.go
Labels: bug

#619 Prevent validators from dropping diags
  internal/fwserver/schema_validation.go
  internal/fwserver/server_validatedatasourceconfig.go
  internal/fwserver/server_validateproviderconfig.go
  internal/fwserver/server_validateresourceconfig.go
Labels: bug

#621 internal/toproto*: Convert null list/set block values to empty
  .changelog/621.txt
  internal/fromproto5/dynamic_value.go
  internal/fromproto6/dynamic_value.go
  internal/fwschemadata/data_nullify_collection_blocks.go
  internal/fwschemadata/data_reify_null_collection_blocks.go
  internal/fwschemadata/data_reify_null_collection_blocks_test.go
  internal/toproto5/applyresourcechange_test.go
  internal/toproto5/config.go
  internal/toproto5/config_test.go
  internal/toproto5/dynamic_value.go
  internal/toproto5/dynamic_value_test.go
  internal/toproto5/importedresource_test.go
  internal/toproto5/planresourcechange_test.go
  internal/toproto5/prepareproviderconfig_test.go
  internal/toproto5/readdatasource_test.go
  internal/toproto5/readresource_test.go
  internal/toproto5/state.go
  internal/toproto5/state_test.go
  internal/toproto5/upgraderesourcestate_test.go
  internal/toproto6/applyresourcechange_test.go
  internal/toproto6/config.go
  internal/toproto6/config_test.go
  internal/toproto6/dynamic_value.go
  internal/toproto6/dynamic_value_test.go
  internal/toproto6/importedresource_test.go
  internal/toproto6/planresourcechange_test.go
  internal/toproto6/readdatasource_test.go
  internal/toproto6/readresource_test.go
  internal/toproto6/state.go
  internal/toproto6/state_test.go
  internal/toproto6/upgraderesourcestate_test.go
  internal/toproto6/validateproviderconfig_test.go
Labels: enhancement

#624 internal/fwschemadata: Prevent single nested block panics in Data ReifyNullCollectionBlocks method
  .changelog/624.txt
  internal/fwschemadata/data_nullify_collection_blocks.go
  internal/fwschemadata/data_reify_null_collection_blocks.go
  internal/fwschemadata/data_reify_null_collection_blocks_test.go
Labels: bug

#626 website: Introduce benefits page to migration guide
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/index.mdx
  website/docs/plugin/framework/migrating/benefits.mdx
  website/docs/plugin/framework/migrating/index.mdx
Labels: documentation

#637 docs: fix for conversion-rules links
  website/docs/plugin/framework/handling-data/accessing-values.mdx
  website/docs/plugin/framework/handling-data/attributes.mdx
  website/docs/plugin/framework/handling-data/writing-state.mdx
Labels: documentation
