Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-04, with the labels that each got.

#712 Fix sample code in the doc
  website/docs/plugin/framework/migrating/resources/index.mdx
Labels: documentation

#715 internal/reflect: Raise framework errors instead of upstream errors or panics with mismatched types
  .changes/unreleased/BUG FIXES-20230404-211215.yaml
  internal/reflect/interfaces.go
  internal/reflect/interfaces_test.go
  internal/reflect/struct.go
  internal/reflect/struct_test.go
Labels: bug, reflection

#711 resource/schema: Prevent UseStateForUnknown data misalignment by raising implementation error when under a list or set
  .changes/unreleased/BUG FIXES-20230406-112757.yaml
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/schema_plan_modification_test.go
  internal/parentpath/doc.go
  internal/parentpath/has_list_or_set.go
  internal/parentpath/has_list_or_set_test.go
  internal/planmodifierdiag/doc.go
  internal/planmodifierdiag/use_state_for_unknown.go
  internal/planmodifierdiag/use_state_for_unknown_test.go
  resource/schema/boolplanmodifier/use_state_for_unknown.go
  resource/schema/boolplanmodifier/use_state_for_unknown_test.go
  resource/schema/float64planmodifier/use_state_for_unknown.go
  resource/schema/float64planmodifier/use_state_for_unknown_test.go
  resource/schema/int64planmodifier/use_state_for_unknown.go
  resource/schema/int64planmodifier/use_state_for_unknown_test.go
  resource/schema/listplanmodifier/use_state_for_unknown.go
  resource/schema/listplanmodifier/use_state_for_unknown_test.go
  resource/schema/mapplanmodifier/use_state_for_unknown.go
  resource/schema/mapplanmodifier/use_state_for_unknown_test.go
  resource/schema/numberplanmodifier/use_state_for_unknown.go
  resource/schema/numberplanmodifier/use_state_for_unknown_test.go
  resource/schema/objectplanmodifier/use_state_for_unknown.go
  resource/schema/objectplanmodifier/use_state_for_unknown_test.go
  resource/schema/setplanmodifier/use_state_for_unknown.go
  resource/schema/setplanmodifier/use_state_for_unknown_test.go
  resource/schema/stringplanmodifier/use_state_for_unknown.go
  resource/schema/stringplanmodifier/use_state_for_unknown_test.go
  website/docs/plugin/framework/resources/plan-modification.mdx
Labels: bug

#719 Update read.mdx
  website/docs/plugin/framework/resources/read.mdx
Labels: documentation

#730 Update index.mdx
  website/docs/plugin/framework/providers/index.mdx
Labels: documentation

#731 Update update.mdx
  website/docs/plugin/framework/resources/update.mdx
Labels: documentation

#733 Correct broken URLs describing attributes+blocks
  website/docs/plugin/framework/migrating/schema/index.mdx
Labels: documentation
