Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-07, with the labels that each got.

#791 types/basetypes: Reduce memory allocations of (ObjectValue).ToTerraformValue()
  .changes/unreleased/BUG FIXES-20230703-123518.yaml
  types/basetypes/object_value.go
  types/basetypes/object_value_test.go
Labels: bug

#790 internal/reflection: Migrate reflection tests for struct tags to exported methods
  internal/reflect/helpers_test.go
  internal/reflect/struct_test.go
Labels: reflection

#797 internal/fwserver: Prevent PlanResourceChange panic during changed path logging
  .changes/unreleased/BUG FIXES-20230711-161747.yaml
  internal/fwschemadata/data_get_at_path_test.go
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_planresourcechange_test.go
Labels: bug

#798 internal/fwserver: Remove old multiple pass code comments in PlanResourceChange logic
  internal/fwserver/server_planresourcechange.go
Labels: tech-debt

#806 internal/reflect: Use underlying terraform-plugin-go types to validate provider given values
  .changes/unreleased/BUG FIXES-20230719-142413.yaml
  internal/reflect/interfaces.go
  internal/reflect/interfaces_test.go
  internal/reflect/struct_test.go
Labels: bug

#807 docs: Use arbitrary with map keys and explicit with object attribute names
  website/docs/plugin/framework/handling-data/attributes.mdx
Labels: documentation
