Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-08, with the labels that each got.

#817 types/basetypes: Fix Float64Attribute precision comparisons
  .changes/unreleased/BUG FIXES-20230803-120411.yaml
  types/basetypes/float64_type.go
  types/basetypes/float64_type_test.go
  types/basetypes/float64_value.go
  types/basetypes/float64_value_test.go
Labels: bug, types

#823 internal/fwserver: Ensure Attribute and Block Plan Modification Returns Custom Value Type Implementations When Using Custom Type NestedAttributeObject/NestedBlockObject
  .changes/unreleased/BUG FIXES-20230816-113531.yaml
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/testing/testschema/nested_attribute.go
  internal/testing/testschema/nested_attribute_object.go
  internal/testing/testschema/nested_attribute_object_custom_type.go
  internal/testing/testschema/nested_attribute_object_list_custom_type.go
  internal/testing/testschema/nested_attribute_object_map_custom_type.go
  internal/testing/testschema/nested_attribute_object_set_custom_type.go
  internal/testing/testschema/nested_block_object.go
Labels: bug

#822 website: Expand data handling documentation with type-specific pages and examples
  .github/CONTRIBUTING.md
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/handling-data/accessing-values.mdx
  website/docs/plugin/framework/handling-data/attributes.mdx
  website/docs/plugin/framework/handling-data/attributes/bool.mdx
  website/docs/plugin/framework/handling-data/attributes/float64.mdx
  website/docs/plugin/framework/handling-data/attributes/index.mdx
  website/docs/plugin/framework/handling-data/attributes/int64.mdx
  website/docs/plugin/framework/handling-data/attributes/list-nested.mdx
  website/docs/plugin/framework/handling-data/attributes/list.mdx
  website/docs/plugin/framework/handling-data/attributes/map-nested.mdx
  website/docs/plugin/framework/handling-data/attributes/map.mdx
  website/docs/plugin/framework/handling-data/attributes/number.mdx
  website/docs/plugin/framework/handling-data/attributes/object.mdx
  website/docs/plugin/framework/handling-data/attributes/set-nested.mdx
  website/docs/plugin/framework/handling-data/attributes/set.mdx
  website/docs/plugin/framework/handling-data/attributes/single-nested.mdx
  website/docs/plugin/framework/handling-data/attributes/string.mdx
  website/docs/plugin/framework/handling-data/blocks.mdx
  website/docs/plugin/framework/handling-data/blocks/index.mdx
  website/docs/plugin/framework/handling-data/blocks/list-nested.mdx
  website/docs/plugin/framework/handling-data/blocks/set-nested.mdx
  website/docs/plugin/framework/handling-data/blocks/single-nested.mdx
  website/docs/plugin/framework/handling-data/conversion-rules.mdx
  website/docs/plugin/framework/handling-data/schemas.mdx
  website/docs/plugin/framework/handling-data/terraform-concepts.mdx
  website/docs/plugin/framework/handling-data/types/bool.mdx
  website/docs/plugin/framework/handling-data/types/custom.mdx
  website/docs/plugin/framework/handling-data/types/float64.mdx
  website/docs/plugin/framework/handling-data/types/index.mdx
  website/docs/plugin/framework/handling-data/types/int64.mdx
  website/docs/plugin/framework/handling-data/types/list.mdx
  website/docs/plugin/framework/handling-data/types/map.mdx
  website/docs/plugin/framework/handling-data/types/number.mdx
  website/docs/plugin/framework/handling-data/types/object.mdx
  website/docs/plugin/framework/handling-data/types/set.mdx
  website/docs/plugin/framework/handling-data/types/string.mdx
  website/docs/plugin/framework/handling-data/writing-state.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
Labels: documentation

#824 website: Use hcl code language fences instead of terraform/tf
  website/docs/plugin/framework/data-sources/timeouts.mdx
  website/docs/plugin/framework/handling-data/terraform-concepts.mdx
  website/docs/plugin/framework/migrating/benefits.mdx
  website/docs/plugin/framework/migrating/data-sources/timeouts.mdx
  website/docs/plugin/framework/migrating/resources/timeouts.mdx
  website/docs/plugin/framework/providers/index.mdx
  website/docs/plugin/framework/resources/timeouts.mdx
Labels: documentation

#825 website: Fix string attributes/types index links
  website/docs/plugin/framework/handling-data/attributes/index.mdx
  website/docs/plugin/framework/handling-data/types/index.mdx
Labels: documentation

#826 Small tweak for licensing language
  .github/CONTRIBUTING.md
Labels: documentation

#830 website: Move acceptance testing id requirement to troubleshooting section
  website/docs/plugin/framework/acctests.mdx
Labels: documentation

#831 website: Add data consistency error migration docs for "planned value does not match config value"
  website/docs/plugin/framework/migrating/index.mdx
  website/docs/plugin/framework/migrating/resources/crud.mdx
  website/docs/plugin/framework/migrating/resources/index.mdx
Labels: documentation
