Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-03, with the labels that each got.

#682 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-091808.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  website/docs/plugin/framework/migrating/index.mdx
Labels: tech-debt

#685 website: Move migration guide muxing content to standalone page
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/migrating/index.mdx
  website/docs/plugin/framework/migrating/mux.mdx
  website/docs/plugin/framework/migrating/providers/index.mdx
  website/docs/plugin/framework/migrating/testing.mdx
Labels: documentation

#688 attr: Fix verbiage for Type and Value type Equal methods
  attr/type.go
  attr/value.go
  types/basetypes/list.go
  types/basetypes/map.go
  types/basetypes/object.go
  types/basetypes/set.go
Labels: documentation

#689 types: Go pointer value constructors and getters for Bool, Float64, Int64, and String
  .changes/unreleased/ENHANCEMENTS-20230314-144231.yaml
  .changes/unreleased/ENHANCEMENTS-20230314-144232.yaml
  .changes/unreleased/ENHANCEMENTS-20230314-144233.yaml
  .changes/unreleased/ENHANCEMENTS-20230314-144234.yaml
  types/basetypes/bool.go
  types/basetypes/bool_test.go
  types/basetypes/float64.go
  types/basetypes/float64_test.go
  types/basetypes/int64.go
  types/basetypes/int64_test.go
  types/basetypes/string.go
  types/basetypes/string_test.go
  types/bool_value.go
  types/float64_value.go
  types/int64_value.go
  types/string_value.go
Labels: enhancement, types

#687 website: Enhance diagnostics page with references to diag.New functions and more examples
  website/docs/plugin/framework/diagnostics.mdx
Labels: documentation

#690 types/basetypes: Lift and shift type versus value code
  types/basetypes/bool_type_test.go
  types/basetypes/bool_value.go
  types/basetypes/bool_value_test.go
  types/basetypes/float64_type_test.go
  types/basetypes/float64_value.go
  types/basetypes/float64_value_test.go
  types/basetypes/int64_type_test.go
  types/basetypes/int64_value.go
  types/basetypes/int64_value_test.go
  types/basetypes/list_type.go
  types/basetypes/list_type_test.go
  types/basetypes/list_value.go
  types/basetypes/list_value_test.go
  types/basetypes/map_type.go
  types/basetypes/map_type_test.go
  types/basetypes/map_value.go
  types/basetypes/map_value_test.go
  types/basetypes/number_type_test.go
  types/basetypes/number_value.go
  types/basetypes/number_value_test.go
  types/basetypes/object_type.go
  types/basetypes/object_type_test.go
  types/basetypes/object_value.go
  types/basetypes/object_value_test.go
  types/basetypes/set_type.go
  types/basetypes/set_type_test.go
  types/basetypes/set_value.go
  types/basetypes/set_value_test.go
  types/basetypes/string_type_test.go
  types/basetypes/string_value.go
  types/basetypes/string_value_test.go
Labels: tech-debt

#694 .github: Contributing guide updates to clarify current stances and recommendations
  .github/CONTRIBUTING.md
Labels: documentation

#684 Add deprecation documentation (from Best Practices - SDKv2)
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/deprecations.mdx
  website/docs/plugin/framework/handling-data/schemas.mdx
Labels: documentation

#697 website: Fix table on Default page
  website/docs/plugin/framework/resources/default.mdx
Labels: documentation

#708 internal/fwschema: Validate leading numerics in attribute names
  .changes/unreleased/ENHANCEMENTS-20230330-105617.yaml
  .changes/unreleased/ENHANCEMENTS-20230330-105618.yaml
  .changes/unreleased/ENHANCEMENTS-20230330-105619.yaml
  internal/fwschema/attribute_name_validation.go
  internal/fwschema/attribute_name_validation_test.go
Labels: enhancement
