Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-11, with the labels that each got.

#871 docs: Add protocol version 6 compatibility note with mux
  website/docs/plugin/framework/provider-servers.mdx
Labels: documentation

#870 types/basetypes: Add Tuple type support
  .changes/unreleased/FEATURES-20231102-160132.yaml
  internal/fromtftypes/value_test.go
  internal/reflect/interfaces_test.go
  internal/reflect/into_test.go
  internal/reflect/outof_test.go
  internal/reflect/slice.go
  types/basetypes/tuple_type.go
  types/basetypes/tuple_type_test.go
  types/basetypes/tuple_value.go
  types/basetypes/tuple_value_test.go
  types/tuple_type.go
  types/tuple_value.go
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/handling-data/types/index.mdx
  website/docs/plugin/framework/handling-data/types/list.mdx
  website/docs/plugin/framework/handling-data/types/set.mdx
  website/docs/plugin/framework/handling-data/types/tuple.mdx
Labels: enhancement, types

#874 .github: Add CI for changie
  .github/workflows/ci-changie.yml
Labels: tech-debt

#876 Updating documentation for testing migration
  website/docs/plugin/framework/migrating/testing.mdx
Labels: documentation

#877 docs: Further clarify SDK migration testing of data sources
  website/docs/plugin/framework/migrating/testing.mdx
Labels: documentation
