Repository hashicorp/terraform-plugin-framework, pull requests merged in 2023-06, with the labels that each got.

#756 Fix example errors in custom-types.mdx
  website/docs/plugin/framework/handling-data/custom-types.mdx
Labels: documentation

#755 types/basetypes: Prevent panics in `ListType`, `MapType`, and `SetType` methods when `ElemType` field is not set
  .changes/unreleased/BUG FIXES-20230609-162628.yaml
  internal/reflect/struct_test.go
  types/basetypes/list_type.go
  types/basetypes/list_type_test.go
  types/basetypes/map_type.go
  types/basetypes/map_type_test.go
  types/basetypes/missing_type.go
  types/basetypes/missing_value.go
  types/basetypes/object_type_test.go
  types/basetypes/set_type.go
  types/basetypes/set_type_test.go
Labels: bug

#762 Adjust `NestedAttributesEqual` to perform shallow compare first
  internal/fwschema/nested_attribute.go
Labels: tech-debt

#769 docs: Additional type-based semantic equality information
  website/docs/plugin/framework/handling-data/custom-types.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/fields.mdx
Labels: documentation

#768 internal/fwserver: Ensure Attribute and Block plan modification returns custom value type implementations
  .changes/unreleased/BUG FIXES-20230613-133402.yaml
  internal/fwserver/attr_type.go
  internal/fwserver/attr_value.go
  internal/fwserver/attribute_plan_modification.go
  internal/fwserver/attribute_plan_modification_test.go
  internal/fwserver/block_plan_modification.go
  internal/fwserver/block_plan_modification_test.go
  internal/fwserver/diagnostics.go
  internal/fwserver/server_planresourcechange_test.go
  internal/testing/testschema/block.go
  internal/testing/testschema/blockwithlistplanmodifiers.go
  internal/testing/testschema/blockwithobjectplanmodifiers.go
  internal/testing/testschema/blockwithsetplanmodifiers.go
Labels: bug

#772 internal/fwschemadata: Prevent panics in `ValueSemanticEqualityListElements` and `ValueSemanticEqualitySetElements` methods when the length of `newValueElements` is greater than `priorValueElements`
  .changes/unreleased/BUG FIXES-20230614-142449.yaml
  internal/fwschemadata/value_semantic_equality_list.go
  internal/fwschemadata/value_semantic_equality_list_test.go
  internal/fwschemadata/value_semantic_equality_set.go
  internal/fwschemadata/value_semantic_equality_set_test.go
Labels: bug

#770 docs: Adjust semantic equality ordering and use stronger wording for overriding methods
  website/docs/plugin/framework/handling-data/custom-types.mdx
Labels: documentation

#771 internal/fwserver: Add unit test for PlanResourceChange with CustomType and Default
  internal/fwserver/server_planresourcechange_test.go
Labels: tech-debt

#780 internal/fwschemadata: Ensure Default implementations receive request Path and have response Diagnostics handled
  .changes/unreleased/BUG FIXES-20230616-140718.yaml
  .changes/unreleased/BUG FIXES-20230616-140834.yaml
  internal/fwschemadata/data_default.go
  internal/fwschemadata/data_default_test.go
  internal/testing/testdefaults/bool.go
  internal/testing/testdefaults/doc.go
  internal/testing/testdefaults/float64.go
  internal/testing/testdefaults/int64.go
  internal/testing/testdefaults/list.go
  internal/testing/testdefaults/map.go
  internal/testing/testdefaults/number.go
  internal/testing/testdefaults/object.go
  internal/testing/testdefaults/set.go
  internal/testing/testdefaults/string.go
Labels: bug

#785 internal/fwserver: Delay resource schema caching to occur after GetProviderSchema RPC
  .changes/unreleased/BUG FIXES-20230623-172651.yaml
  internal/fwserver/server.go
  internal/proto5server/server_getproviderschema_test.go
  internal/proto6server/server_getproviderschema_test.go
Labels: bug
