Repository hashicorp/terraform-plugin-framework, pull requests merged in 2024-03, with the labels that each got.

#933 resource/schema: Ensure invalid attribute default value errors are raised
  .changes/unreleased/BUG FIXES-20240228-103338.yaml
  internal/fwschema/diagnostics.go
  internal/fwschemadata/data_default.go
  internal/fwschemadata/data_default_test.go
  resource/schema/list_attribute.go
  resource/schema/list_attribute_test.go
  resource/schema/list_nested_attribute.go
  resource/schema/list_nested_attribute_test.go
  resource/schema/map_attribute.go
  resource/schema/map_attribute_test.go
  resource/schema/map_nested_attribute.go
  resource/schema/map_nested_attribute_test.go
  resource/schema/object_attribute.go
  resource/schema/object_attribute_test.go
  resource/schema/set_attribute.go
  resource/schema/set_attribute_test.go
  resource/schema/set_nested_attribute.go
  resource/schema/set_nested_attribute_test.go
  resource/schema/single_nested_attribute.go
  resource/schema/single_nested_attribute_test.go
Labels: bug

#940 Update provider functions testing docs to help users avoid nil pointer error
  website/docs/plugin/framework/functions/testing.mdx
Labels: documentation

#937 Reinstate go toolchain and add changelog for Go version bump to 1.21
  .changes/unreleased/NOTES-20240229-142101.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  tools/go.mod
  tools/go.sum
  website/docs/plugin/framework/migrating/index.mdx
Labels: dependencies

#942 Fixing Documentation for Defining Type Validation
  website/docs/plugin/framework/validation.mdx
Labels: documentation

#945 docs: Include tfversion checking in function acceptance testing
  website/docs/plugin/framework/functions/testing.mdx
Labels: documentation

#949 `attr.Value` → `attr.Type`
  website/docs/plugin/framework/functions/returns/object.mdx
Labels: documentation

#950 website/docs: Fix object parameter attr.Type example
  website/docs/plugin/framework/functions/parameters/object.mdx
Labels: documentation

#951 Add clarification for nil check of ProviderData in data source and resource Configure() method
  website/docs/plugin/framework/data-sources/configure.mdx
  website/docs/plugin/framework/resources/configure.mdx
Labels: documentation

#952 docs: Fix note tag with link
  website/docs/plugin/framework/functions/index.mdx
Labels: documentation

#957 Correct resource State Move documentation
  website/docs/plugin/framework/resources/state-move.mdx
Labels: documentation

#956 docs: Explicitly call out object parameter attributes are required
  website/docs/plugin/framework/functions/parameters/object.mdx
Labels: documentation

#958 all: Miscellaneous doc fixes
  internal/fwserver/server_deleteresource.go
  resource/resource.go
  resource/schema/defaults/string.go
  resource/schema/planmodifier/bool.go
  resource/schema/planmodifier/float64.go
  resource/schema/planmodifier/int64.go
  resource/schema/planmodifier/list.go
  resource/schema/planmodifier/map.go
  resource/schema/planmodifier/number.go
  resource/schema/planmodifier/object.go
  resource/schema/planmodifier/set.go
  resource/schema/planmodifier/string.go
  schema/validator/bool.go
  schema/validator/float64.go
  schema/validator/int64.go
  schema/validator/list.go
  schema/validator/map.go
  schema/validator/number.go
  schema/validator/object.go
  schema/validator/set.go
  schema/validator/string.go
Labels: documentation

#960 website/docs: Link fix on int64 type page
  website/docs/plugin/framework/handling-data/types/int64.mdx
Labels: documentation

#964 Require provider-defined function parameter naming
  .changes/unreleased/BREAKING CHANGES-20240320-095152.yaml
  .changes/unreleased/BREAKING CHANGES-20240320-171454.yaml
  function/definition.go
  function/definition_test.go
  function/func_error.go
  function/func_error_test.go
  function/parameter.go
  internal/fwserver/server_functions.go
  internal/fwserver/server_getfunctions_test.go
  internal/fwserver/server_getproviderschema_test.go
  internal/toproto5/function.go
  internal/toproto5/function_test.go
  internal/toproto5/getfunctions_test.go
  internal/toproto5/getproviderschema_test.go
  internal/toproto6/function.go
  internal/toproto6/function_test.go
  internal/toproto6/getfunctions_test.go
  internal/toproto6/getproviderschema_test.go
  website/docs/plugin/framework/functions/documentation.mdx
  website/docs/plugin/framework/functions/implementation.mdx
  website/docs/plugin/framework/functions/parameters/bool.mdx
  website/docs/plugin/framework/functions/parameters/float64.mdx
  website/docs/plugin/framework/functions/parameters/index.mdx
  website/docs/plugin/framework/functions/parameters/int64.mdx
  website/docs/plugin/framework/functions/parameters/list.mdx
  website/docs/plugin/framework/functions/parameters/map.mdx
  website/docs/plugin/framework/functions/parameters/number.mdx
  website/docs/plugin/framework/functions/parameters/object.mdx
  website/docs/plugin/framework/functions/parameters/set.mdx
  website/docs/plugin/framework/functions/parameters/string.mdx
Labels: breaking-change

#970 internal/fwserver: Ensure computed dynamic values are marked as dynamic type during plan modification
  .changes/unreleased/BUG FIXES-20240325-101108.yaml
  internal/fwserver/server_planresourcechange.go
  internal/fwserver/server_planresourcechange_test.go
Labels: bug
