Repository hashicorp/terraform-plugin-framework, pull requests merged in 2024-02, with the labels that each got.

#917 resource: Initial MoveResourceState RPC support
  .changes/unreleased/FEATURES-20240201-173428.yaml
  internal/fromproto5/moveresourcestate.go
  internal/fromproto5/moveresourcestate_test.go
  internal/fromproto6/moveresourcestate.go
  internal/fromproto6/moveresourcestate_test.go
  internal/fwserver/server_capabilities.go
  internal/fwserver/server_getmetadata_test.go
  internal/fwserver/server_getproviderschema_test.go
  internal/fwserver/server_moveresourcestate.go
  internal/fwserver/server_moveresourcestate_test.go
  internal/fwserver/server_upgraderesourcestate.go
  internal/proto5server/server_moveresourcestate.go
  internal/proto5server/server_moveresourcestate_test.go
  internal/proto6server/server_moveresourcestate.go
  internal/proto6server/server_moveresourcestate_test.go
  internal/testing/testprovider/resourcewithmovestate.go
  internal/toproto5/moveresourcestate.go
  internal/toproto5/moveresourcestate_test.go
  internal/toproto6/moveresourcestate.go
  internal/toproto6/moveresourcestate_test.go
  resource/move_state.go
  resource/resource.go
  resource/state_mover.go
  website/data/plugin-framework-nav-data.json
  website/docs/plugin/framework/resources/state-move.mdx
Labels: enhancement

#923 function: Switch the representation of variadic arguments to `types.Tuple`
  .changes/unreleased/BREAKING CHANGES-20240216-142501.yaml
  function/arguments_data.go
  function/arguments_data_test.go
  function/definition.go
  internal/fromproto5/arguments_data.go
  internal/fromproto5/arguments_data_test.go
  internal/fromproto6/arguments_data.go
  internal/fromproto6/arguments_data_test.go
  internal/fwserver/server_callfunction_test.go
  internal/proto5server/server_callfunction_test.go
  internal/proto6server/server_callfunction_test.go
  internal/reflect/into_test.go
  internal/reflect/outof_test.go
  internal/reflect/slice.go
  path/path.go
  path/path_test.go
  website/docs/plugin/framework/functions/implementation.mdx
  website/docs/plugin/framework/handling-data/types/tuple.mdx
Labels: bug, breaking-change, reflection

#851 docs: add import statements to default-values.mdx
  website/docs/plugin/framework/migrating/attributes-blocks/default-values.mdx
Labels: documentation

#919 reflect: Determine equivalency of float32 or float64, and *big.Float via string representation
  internal/reflect/number.go
  internal/reflect/number_test.go
  internal/reflect/options.go
Labels: bug, types, reflection

#935 fix: remove incorrect code in `Diagnostics.Append` - fixes #932
  diag/diagnostics.go
Labels: bug

#936 function: Add validation for parameter name conflicts and update defaulting logic
  .changes/unreleased/BUG FIXES-20240228-151959.yaml
  .changes/unreleased/BUG FIXES-20240228-152155.yaml
  function/bool_parameter.go
  function/bool_parameter_test.go
  function/definition.go
  function/definition_test.go
  function/float64_parameter.go
  function/float64_parameter_test.go
  function/int64_parameter.go
  function/int64_parameter_test.go
  function/list_parameter.go
  function/list_parameter_test.go
  function/map_parameter.go
  function/map_parameter_test.go
  function/number_parameter.go
  function/number_parameter_test.go
  function/object_parameter.go
  function/object_parameter_test.go
  function/parameter.go
  function/set_parameter.go
  function/set_parameter_test.go
  function/string_parameter.go
  function/string_parameter_test.go
  internal/toproto5/function.go
  internal/toproto5/function_test.go
  internal/toproto5/getfunctions_test.go
  internal/toproto5/getproviderschema_test.go
  internal/toproto6/function.go
  internal/toproto6/function_test.go
  internal/toproto6/getfunctions_test.go
  internal/toproto6/getproviderschema_test.go
  website/docs/plugin/framework/functions/documentation.mdx
Labels: bug
